Application\ChiaBundle\Entity\Contact:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string(255)
    title:
      type: string(255)
      nullable: true
    code:
      type: string(100)
      unique: true
      nullable: true
    type:
      type: smallint
    description:
      type: string
      length: null
      nullable: true
  oneToMany:
    people:
      targetEntity: Contact
      mappedBy: company
  manyToOne:
    company:
      targetEntity: Contact
      inversedBy: people
  lifecycleCallbacks: {  }
