Application\ChiaBundle\Entity\Contact:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string(255)
    title:
      type: string(255)
    code:
      type: string(100)
      unique: true
    type:
      type: smallint
    description:
      type: string
      length: null
  lifecycleCallbacks: {  }
