Application\ChiaBundle\Entity\Status:
  type: entity
  table: null
  repositoryClass: Application\ChiaBundle\Entity\StatusRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string(100)
    value:
      type: smallint
  oneToMany:
    projects:
      targetEntity: Project
      mappedBy: status
