Application\ChiaBundle\Entity\Contact:
  type: entity
  table: null
  repositoryClass: Application\ChiaBundle\Entity\ContactRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string(255)
    title:
      type: string(255)
      nullable: true
    code:
      type: string(100)
      unique: true
      nullable: true
    type:
      type: smallint
    description:
      type: string
      length: null
      nullable: true
  oneToMany:
    people:
      targetEntity: Contact
      mappedBy: company
    phonenumbers:
      targetEntity: Phonenumber
      mappedBy: contact
    emails:
      targetEntity: Email
      mappedBy: contact
    addresses:
      targetEntity: Address
      mappedBy: contact
    projects:
      targetEntity: Project
      mappedBy: contact
  manyToOne:
    company:
      targetEntity: Contact
      inversedBy: people
  lifecycleCallbacks: {  }
